CREATE TABLE [dbo].[NewsStory](
	[NewsStoryId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](100) NULL,
	[Blurb] [nvarchar](100) NULL,
	[MainBody] [nvarchar](100) NULL,
	[AuthorName] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[NewsStoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
